spring:
  application:
    name: springboot-init
# todo MySQL????? ?????????????
  datasource:
    url: jdbc:mysql://localhost:3306/init_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8101
